aws:
  version: '%env(AWS_VERSION)%'
  region: '%env(AWS_REGION)%'
  credentials:
    key: "%env(AWS_KEY)%"
    secret: "%env(AWS_SECRET)%"
  S3:
    version: '%env(AWS_S3_VERSION)%'
    region: '%env(AWS_S3_REGION)%'
