parameters:
  mlp.packages.dir: '%kernel.project_dir%/tests/Common/packages'
  mlp.translations.dir: '%kernel.project_dir%/tests/Common/translations'

services:
  transifex.test.client:
    class: App\Tests\Common\Client\TransifexTestClient
    public: true

  request.factory:
    class: Http\Factory\Guzzle\RequestFactory

  stream.factory:
    class: Http\Factory\Guzzle\StreamFactory

  uri.factory:
    class: Http\Factory\Guzzle\UriFactory

  mautic.transifex.config:
    class: Mautic\Transifex\Config
    calls:
      - [ 'setApiToken', [ '%env(TRANSIFEX_API_TOKEN)%' ] ]
      - [ 'setOrganization', [ '%env(TRANSIFEX_ORGANISATION)%' ] ]
      - [ 'setProject', [ '%env(TRANSIFEX_PROJECT)%' ] ]

  mautic.transifex.api.connector:
    class: Mautic\Transifex\ApiConnector
    arguments: [ '@transifex.test.client', '@request.factory', '@stream.factory', '@uri.factory', '@mautic.transifex.config' ]

  mautic.transifex:
    class: Mautic\Transifex\Transifex
    arguments: [ '@transifex.test.client', '@request.factory', '@stream.factory', '@uri.factory', '@mautic.transifex.config' ]
