parameters:
  mlp.packages.dir: '%kernel.project_dir%/tests/Common/packages'
  mlp.translations.dir: '%kernel.project_dir%/tests/Common/translations'

services:
  http.client.mock_handler:
    class: GuzzleHttp\Handler\MockHandler

  http.client:
    class: GuzzleHttp\Client
    factory: [ 'App\Tests\Common\Client\ClientFactory', 'create' ]
    arguments:
      $handler: '@http.client.mock_handler'

  Psr\Http\Client\ClientInterface: '@http.client'
